import os
import json
import logging
from typing import Dict, List, Any, Optional
from core.models.workflow import WorkflowDefinition, WorkflowStep

logger = logging.getLogger("buzzcaf_ai.core.workflow")

WORKFLOWS_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "prompts", "workflows")

class WorkflowRegistry:
    _instance = None
    
    def __new__(cls):
        if cls._instance is None:
            cls._instance = super(WorkflowRegistry, cls).__new__(cls)
            cls._instance.workflows: Dict[str, WorkflowDefinition] = {}
            cls._instance.discover_workflows()
        return cls._instance

    def discover_workflows(self):
        """Automatically discover workflows from the directory on startup."""
        self.workflows.clear()
        if not os.path.exists(WORKFLOWS_DIR):
            os.makedirs(WORKFLOWS_DIR, exist_ok=True)
            return

        for f_name in os.listdir(WORKFLOWS_DIR):
            if f_name.endswith(".json"):
                f_path = os.path.join(WORKFLOWS_DIR, f_name)
                try:
                    with open(f_path, "r", encoding="utf-8") as f:
                        data = json.load(f)
                    
                    steps = [WorkflowStep(**s) for s in data.get("steps", [])]
                    wf = WorkflowDefinition(
                        id=data["id"],
                        name=data["name"],
                        description=data["description"],
                        steps=steps
                    )
                    
                    # Validate before registering
                    self.validate(wf)
                    self.workflows[wf.id] = wf
                    logger.info(f"WorkflowRegistry: Discovered and registered workflow '{wf.id}'")
                except Exception as e:
                    logger.error(f"WorkflowRegistry: Failed to load workflow '{f_name}': {e}")

    def register(self, wf: WorkflowDefinition):
        self.validate(wf)
        self.workflows[wf.id] = wf
        logger.info(f"WorkflowRegistry: Manually registered workflow '{wf.id}'")

    def unregister(self, workflow_id: str):
        if workflow_id in self.workflows:
            del self.workflows[workflow_id]
            logger.info(f"WorkflowRegistry: Unregistered workflow '{workflow_id}'")

    def get(self, workflow_id: str) -> Optional[WorkflowDefinition]:
        return self.workflows.get(workflow_id)

    def list(self) -> List[WorkflowDefinition]:
        return list(self.workflows.values())

    def validate(self, wf: WorkflowDefinition):
        """Ensure valid definitions, no circular dependencies, and agent validation."""
        if not wf.id or not wf.name or not wf.steps:
            raise ValueError(f"Workflow '{wf.id}' is missing required fields (id, name, steps).")

        # 1. Validate agents
        # List of registered agents from AgentRegistry
        valid_agents = ["ceo", "researchagent", "writeragent", "editoragent", "creativedirectoragent", "seomanageragent"]
        for step in wf.steps:
            if step.agent_role.lower().strip() not in valid_agents:
                raise ValueError(f"Workflow '{wf.id}' validation error: Agent '{step.agent_role}' at step '{step.name}' is not in the Agent Registry.")

        # 2. Check circular dependencies in input assets
        # Build dependency graph
        # For each step, it generates an output_asset_type.
        # It relies on input_assets (which must be generated by previous steps).
        asset_producers = {}
        for step in wf.steps:
            if step.output_asset_type:
                asset_producers[step.output_asset_type] = step.name

        # Check topological sorting or check cycle
        # A step must only depend on assets that have already been declared by PREVIOUS steps.
        declared_assets = set()
        for step in wf.steps:
            for input_asset in step.input_assets:
                if input_asset not in declared_assets:
                    # Depends on an asset not yet created!
                    if input_asset in asset_producers:
                        producer = asset_producers[input_asset]
                        raise ValueError(f"Workflow '{wf.id}' validation error: Step '{step.name}' has circular or backward dependency. It requires asset '{input_asset}' which is generated by step '{producer}' (runs later).")
                    else:
                        # Asset is not produced by anyone in the workflow
                        logger.warning(f"Workflow '{wf.id}' warning: Step '{step.name}' requires asset '{input_asset}' which is not produced in this workflow. Assuming external.")
            if step.output_asset_type:
                declared_assets.add(step.output_asset_type)

workflow_registry = WorkflowRegistry()
